config/routes.rb
Rails.application.routes.draw do
  resources :money_managers
  resources :transactions
  resources :games
  resources :squares
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"

  # TODO
  # Needs to create routes path for new actions
end

app/models/square.rb
class Square < ApplicationRecord
  belongs_to :owner, class_name: 'Player', foreign_key: 'owner_id'
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController
  before_action :set_square, only: %i[ show edit update destroy ]

  # TODO
  def property_check
  end

  # GET /squares or /squares.json
  def index
    @squares = Square.all
  end

  # GET /squares/1 or /squares/1.json
  def show
  end

  # GET /squares/new
  def new
    @square = Square.new
  end

  # GET /squares/1/edit
  def edit
  end

  # POST /squares or /squares.json
  def create
    @square = Square.new(square_params)

    respond_to do |format|
      if @square.save
        format.html { redirect_to square_url(@square), notice: "Square was successfully created." }
        format.json { render :show, status: :created, location: @square }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squares/1 or /squares/1.json
  def update
    respond_to do |format|
      if @square.update(square_params)
        format.html { redirect_to square_url(@square), notice: "Square was successfully updated." }
        format.json { render :show, status: :ok, location: @square }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @square.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squares/1 or /squares/1.json
  def destroy
    @square.destroy

    respond_to do |format|
      format.html { redirect_to squares_url, notice: "Square was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_square
      @square = Square.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def square_params
      params.fetch(:square, {})
    end
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/views/squares/_form.html.erb
<%= form_with(model: square) do |form| %>
  <% if square.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(square.errors.count, "error") %> prohibited this square from being saved:</h2>

      <ul>
        <% square.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/squares/_square.html.erb
<div id="<%= dom_id square %>">
</div>

app/views/squares/edit.html.erb
<h1>Editing square</h1>

<%= render "form", square: @square %>

<br>

<div>
  <%= link_to "Show this square", @square %> |
  <%= link_to "Back to squares", squares_path %>
</div>

app/views/squares/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Squares</h1>

<div id="squares">
  <% @squares.each do |square| %>
    <%= render square %>
    <p>
      <%= link_to "Show this square", square %>
    </p>
  <% end %>
</div>

<%= link_to "New square", new_square_path %>

app/views/squares/new.html.erb
<h1>New square</h1>

<%= render "form", square: @square %>

<br>

<div>
  <%= link_to "Back to squares", squares_path %>
</div>

app/views/squares/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @square %>

<div>
  <%= link_to "Edit this square", edit_square_path(@square) %> |
  <%= link_to "Back to squares", squares_path %>

  <%= button_to "Destroy this square", @square, method: :delete %>
</div>