config/routes.rb
Rails.application.routes.draw do
  resources :money_managers
  resources :transactions
  resources :games
  resources :squares
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#index"

  # TODO
  # Needs to create routes path for new actions
end

app/models/money_manager.rb
class MoneyManager < ApplicationRecord
end

app/controllers/money_managers_controller.rb
class MoneyManagersController < ApplicationController
  before_action :set_money_manager, only: %i[ show edit update destroy ]

  # GET /money_managers or /money_managers.json
  def index
    @money_managers = MoneyManager.all
  end

  # GET /money_managers/1 or /money_managers/1.json
  def show
  end

  # GET /money_managers/new
  def new
    @money_manager = MoneyManager.new
  end

  # GET /money_managers/1/edit
  def edit
  end

  # POST /money_managers or /money_managers.json
  def create
    @money_manager = MoneyManager.new(money_manager_params)

    respond_to do |format|
      if @money_manager.save
        format.html { redirect_to money_manager_url(@money_manager), notice: "Money manager was successfully created." }
        format.json { render :show, status: :created, location: @money_manager }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @money_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_managers/1 or /money_managers/1.json
  def update
    respond_to do |format|
      if @money_manager.update(money_manager_params)
        format.html { redirect_to money_manager_url(@money_manager), notice: "Money manager was successfully updated." }
        format.json { render :show, status: :ok, location: @money_manager }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @money_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_managers/1 or /money_managers/1.json
  def destroy
    @money_manager.destroy

    respond_to do |format|
      format.html { redirect_to money_managers_url, notice: "Money manager was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_manager
      @money_manager = MoneyManager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def money_manager_params
      params.fetch(:money_manager, {})
    end
end

app/helpers/money_managers_helper.rb
module MoneyManagersHelper
end

app/views/money_managers/_form.html.erb
<%= form_with(model: money_manager) do |form| %>
  <% if money_manager.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(money_manager.errors.count, "error") %> prohibited this money_manager from being saved:</h2>

      <ul>
        <% money_manager.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/money_managers/_money_manager.html.erb
<div id="<%= dom_id money_manager %>">
</div>

app/views/money_managers/edit.html.erb
<h1>Editing money manager</h1>

<%= render "form", money_manager: @money_manager %>

<br>

<div>
  <%= link_to "Show this money manager", @money_manager %> |
  <%= link_to "Back to money managers", money_managers_path %>
</div>

app/views/money_managers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Money managers</h1>

<div id="money_managers">
  <% @money_managers.each do |money_manager| %>
    <%= render money_manager %>
    <p>
      <%= link_to "Show this money manager", money_manager %>
    </p>
  <% end %>
</div>

<%= link_to "New money manager", new_money_manager_path %>

app/views/money_managers/new.html.erb
<h1>New money manager</h1>

<%= render "form", money_manager: @money_manager %>

<br>

<div>
  <%= link_to "Back to money managers", money_managers_path %>
</div>

app/views/money_managers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @money_manager %>

<div>
  <%= link_to "Edit this money manager", edit_money_manager_path(@money_manager) %> |
  <%= link_to "Back to money managers", money_managers_path %>

  <%= button_to "Destroy this money manager", @money_manager, method: :delete %>
</div>